{{- if .Values.secrets }}
apiVersion: v1
kind: Secret

metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
  labels: {{ include "pgbouncer.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-2"

type: Opaque

stringData:
{{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | toString | quote }}
  {{- end }}
{{- end }}
