{{- if .Values.secrets }}
apiVersion: v1
kind: Secret

metadata:
  name: {{ .Values.pgbouncer.config.existingUserlistSecret }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "pgbouncer.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"

type: Opaque

stringData:
  userlist.txt: | {{ include "pgbouncer.userlist" . | indent 4 }}
{{- end }}
