postgresql:
  fullnameOverride: postgresql

  architecture: standalone

  auth:
    existingSecret: postgresql-secrets
    secretKeys:
      adminPasswordKey: POSTGRES_ADMIN_PASSWORD

  primary:
    extendedConfiguration: |
      max_connections = 610                 # (default_pool_size * db_count) + admin_slots
      shared_buffers = 1GB                  # 25% of limits memory
      work_mem = 4MB                        # memory per connection for queries
      maintenance_work_mem = 256MB          # memory for maintenance tasks (VACUUM, CREATE INDEX)
      checkpoint_completion_target = 0.9    # how aggressively to complete checkpoints
      wal_buffers = 16MB                    # memory for WAL (Write-Ahead Log) buffers
      effective_cache_size = 3GB            # estimate of OS cache available for queries

    persistence:
      storageClass: local-postgresql
      size: 10Gi

    persistentVolumeClaimRetentionPolicy:
      enabled: true

    resources:
      requests:
        cpu: 500m
        memory: 2048Mi
      limits:
        cpu: 1000m
        memory: 4096Mi
