apiVersion: v1
kind: Secret

metadata:
  name: {{ .Values.cloudflare.apiTokenSecretRef.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"

type: Opaque

stringData:
  {{ .Values.cloudflare.apiTokenSecretRef.key }}: {{ .Values.secrets.CLOUDFLARE_API_TOKEN | quote }}
