apiVersion: cert-manager.io/v1
kind: Certificate

metadata:
  name: {{ .Values.certificate.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-2"

spec:
  secretName: {{ .Values.certificate.name }}
  issuerRef:
    name: {{ .Values.certificate.issuerName }}
    kind: ClusterIssuer

  commonName: {{ .Values.certificate.commonName | quote}}
  dnsNames: {{ toYaml .Values.certificate.dnsNames | nindent 4 }}

  privateKey:
    algorithm: RSA
    size: 2048

  usages:
    - digital signature
    - key encipherment
    - server auth
