{{- if .Values.certificate.cronJob.enabled }}
apiVersion: v1
kind: ServiceAccount

metadata:
  name: {{ .Values.certificate.cronJob.RBAC.name }}
  namespace: {{ .Release.Namespace }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role

metadata:
  name: {{ .Values.certificate.cronJob.RBAC.roleName }}
  namespace: {{ .Release.Namespace }}

rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]

  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "create", "update", "patch"]

  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "patch", "update"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding

metadata:
  name: tls-cron-binding
  namespace: {{ .Release.Namespace }}

subjects:
  - kind: ServiceAccount
    name: {{ .Values.certificate.cronJob.RBAC.name }}
    namespace: {{ .Release.Namespace }}

roleRef:
  kind: Role
  name: {{ .Values.certificate.cronJob.RBAC.roleName }}
  apiGroup: rbac.authorization.k8s.io

{{- end }}
