service:
  replicaCount: 1

  image:
    repository: mimspace/docs-service

  resources:
    requests:
      cpu: 25m
      memory: 32Mi
    limits:
      cpu: 50m
      memory: 64Mi

  migrations:
    enabled: false

  autoscaling:
    enabled: false

  livenessProbe:
    enabled: false

  readinessProbe:
    enabled: false

  env:
    SERVICES: '["auth"]'
