{{- if .Values.env }}
apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-2"

data:
{{- range $key, $value := .Values.env }}
  {{- if contains "\n" ($value | toString) }}
  {{ $key }}: | {{ $value | toString | nindent 4 }}
  {{- else }}
  {{ $key }}: {{ $value | toString | quote }}
  {{- end }}
{{- end }}
{{- end }}
