{{- if .Values.secrets }}
apiVersion: v1
kind: Secret

metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-2"

type: Opaque

stringData:
{{- range $key, $value := .Values.secrets }}
  {{- if contains "\n" ($value | toString) }}
  {{ $key }}: | {{ $value | toString | nindent 4 }}
  {{- else }}
  {{ $key }}: {{ $value | toString | quote }}
  {{- end }}
{{- end }}
{{- end }}
